### PR TITLE
Fix resizer on absolute drag mode when the parent is positioned ( position: relative | absolute | .... )

### LINKED ISSUE #6373: BUG: Resizing of Child with absolute drag enabled positions element wrongly when in Parent with relative position
### GrapesJS version

- [x] I confirm to use the latest version of GrapesJS

### What browser are you using?

Version 131.0.6778.265

### Reproducible demo link

https://codepen.io/chipikaf/pen/KwPexjL

### Describe the bug

**How to reproduce the bug?**
1. Drop the button component in the Middle section
2. Move the button anywhere in the section
3. Resize element

**What is the expected behavior?**
For the element to be resized in its original position

**What is the current behavior?**
The element is moved below to an unexpected position

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mohamedsalem401**
For https://github.com/GrapesJS/grapesjs/issues/6373

### CODE REVIEW

File: packages/core/src/utils/Resizer.ts [hunk 1]
```diff
@@ -750,4 +756,20 @@ export default class Resizer {
...
+    while (currentElement) {
+      const position = window.getComputedStyle(currentElement).position;
+      if (position === 'relative' || position === 'absolute' || position === 'fixed' || position === 'sticky') {
+        return true;
+      }
+      currentElement = currentElement.parentElement;
+    }
+
+    return false;
+  }
```
Comment (artf) [inline packages/core/src/utils/Resizer.ts]: this looks expensive, can't we simply rely on [`offsetParent`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent)?

**Review by artf — APPROVED** [review]
