### PR TITLE
Performance improvements

### LINKED ISSUE #6618: BUG: Improve Editor performance and fix any memory leak
### GrapesJS version

- [x] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome 

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

- Fix passing down `collectionsSourceMap` if not needed
- Insure that all listeners are cleaned if not needed
- Improve `Editor.loadProject` speed

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mohamedsalem401**
Related to #6618

### CODE REVIEW

File: packages/core/src/abstract/Module.ts [hunk 1]
```diff
@@ -130,6 +130,7 @@ export abstract class ItemManagerModule<
   all: TCollection;
   view?: View;
   events!: Record<string, string>;
+  protected _itemCache = new Map<string, any>();
```
Comment (artf) [inline packages/core/src/abstract/Module.ts]: `new Map<string, Model>`

File: packages/core/src/selector_manager/index.ts [hunk 2]
```diff
@@ -152,16 +150,34 @@ export default class SelectorManager extends ItemManagerModule<SelectorManagerCo
...
+    this._setupListeners();
+    this._onItemsReset(this.all);
     this.__initListen({
       collections: [this.states, this.selected],
       propagate: [{ entity: this.states, event: this.events.state }],
     });
-    em.on('change:state', (m, value) => em.trigger(evState, value));
-    this.model.on('change:cFirst', (m, value) => em.trigger('selector:type', value));
+
+    const { em: editor } = this;
```
Comment (artf) [inline packages/core/src/selector_manager/index.ts]: to rollback

File: packages/core/src/abstract/Module.ts [hunk 3]
```diff
@@ -207,6 +208,64 @@ export abstract class ItemManagerModule<
...
+    }
+
+    if (oldKey) {
+      this._itemCache.delete(oldKey);
+    }
+
+    this._cacheItem(item);
+  }
+
+  protected _setupListeners() {
```
Comment (artf) [inline packages/core/src/abstract/Module.ts]: `_setupCacheListeners`

File: packages/core/src/abstract/Module.ts [hunk 4]
```diff
@@ -207,6 +208,64 @@ export abstract class ItemManagerModule<
...
+    this.em.listenTo(this.all, 'add', this._onItemAdd.bind(this));
+    this.em.listenTo(this.all, 'remove', this._onItemRemove.bind(this));
+    this.em.listenTo(this.all, 'reset', this._onItemsReset.bind(this));
```
Comment (artf) [inline packages/core/src/abstract/Module.ts]: is bind necessary?

I'd also expect this to be the same
```js
this.all.on('add', this._onItemAdd)
```

File: packages/core/src/abstract/Module.ts [hunk 5]
```diff
@@ -207,6 +208,64 @@ export abstract class ItemManagerModule<
...
+    this._itemCache.clear();
+  }
+
+  protected _onItemAdd(item: Model) {
+    this._cacheItem(item);
+  }
+
+  protected _onItemRemove(item: Model) {
+    this._uncacheItem(item);
+  }
```
Comment (artf) [inline packages/core/src/abstract/Module.ts]: I think these could be removed

File: packages/core/src/abstract/Module.ts [hunk 6]
```diff
@@ -207,6 +208,64 @@ export abstract class ItemManagerModule<
...
+
+  protected _onItemsReset(collection: Collection) {
```
Comment (artf) [inline packages/core/src/abstract/Module.ts]: `_onItemsResetCache`

File: packages/core/src/abstract/Module.ts [hunk 7]
```diff
@@ -207,6 +208,64 @@ export abstract class ItemManagerModule<
...
   }
 
+  protected _makeCacheKey(selectors: any, state?: string, width?: string) {
+    const sels = Array.isArray(selectors)
+      ? selectors.map((s) => (typeof s === 'string' ? s : s.toString())).join(',')
+      : typeof selectors === 'string'
+        ? selectors
+        : selectors?.toString() || '';
+    return `${sels}|${state || ''}|${width || ''}`;
+  }
```
Comment (artf) [inline packages/core/src/abstract/Module.ts]:
```js
protected _makeCacheKey(m: Model) {
  return '';
}
```

File: packages/core/src/abstract/Module.ts [hunk 8]
```diff
@@ -207,6 +208,64 @@ export abstract class ItemManagerModule<
...
+
+  protected _cacheItem(item: Model) {
+    const key = this._makeCacheKey(item);
+    this._itemCache.set(key, item);
```
Comment (artf) [inline packages/core/src/abstract/Module.ts]:
```js
const key = this._makeCacheKey(item);
key && this._itemCache.set(key, item);
```

File: packages/core/src/abstract/Module.ts [hunk 9]
```diff
@@ -207,6 +208,64 @@ export abstract class ItemManagerModule<
...
+  }
+
+  protected _uncacheItem(item: Model) {
+    const key = this._makeCacheKey(item);
+    this._itemCache.delete(key);
```
Comment (artf) [inline packages/core/src/abstract/Module.ts]: the same above

File: packages/core/src/css_composer/index.ts [hunk 10]
```diff
@@ -87,7 +87,7 @@ export default class CssComposer extends ItemManagerModule<CssComposerConfig & {
   Selectors = Selectors;
 
   storageKey = 'styles';
-
+  private _ruleCache = new Map<string, CssRule>();
```
Comment (artf) [inline packages/core/src/css_composer/index.ts]: protected _itemCache = new Map<string, CssRule>();

File: packages/core/src/css_composer/index.ts [hunk 11]
```diff
@@ -104,6 +104,12 @@ export default class CssComposer extends ItemManagerModule<CssComposerConfig & {
     config.rules = this.em.config.style || config.rules || '';
 
     this.rules = new CssRules([], config);
+    this._setupListeners();
+  }
+
```
Comment (artf) [inline packages/core/src/css_composer/index.ts:109]: we need a default way to cache CssRule
```js
_makeCacheKey(rule) {
    const atRuleKey = rule.getAtRule();
    const selectorsKey = rule.selectorsToString();
    return `${atRuleKey}__${selectorsKey}`;
}
```

File: packages/core/src/css_composer/index.ts [hunk 12]
```diff
@@ -157,27 +164,27 @@ export default class CssComposer extends ItemManagerModule<CssComposerConfig & {
     const s = state || '';
     const w = width || '';
     const opt = { ...opts } as CssRuleProperties;
-    let rule = this.get(selectors, s, w, opt);
+    const key = this._makeCacheKey(selectors, s, w);
```
Comment (artf) [inline packages/core/src/css_composer/index.ts]: we have to add a new method in css manager to get a key from these props, eg.
```js
_makeCacheKeyFromProps(ruleProps) {
    const { atRuleType = '', mediaText = '', state = '', selectorsAdd = '', selectors = [] } = ruleProps;

    const selectorsStr = (selectors as string[]).map(str => (str.startsWith('#') ? str : `.${str}`)).join('');
    const selectorsRes = [];
    selectorsStr && selectorsRes.push(`${selectorsStr}${state ? `:${state}` : ''}`);
    selectorsAdd && selectorsRes.push(selectorsAdd);
    const selectorsKey = selectorsRes.join(', ');

    const typeStr = atRuleType ? `@${atRuleType}` : mediaText ? '@media' : '';
    const atRuleKey = typeStr + (mediaText && typeStr ? ` ${mediaText}` : '');

    return `${atRuleKey}__${selectorsKey}`;
}
```

File: packages/core/src/css_composer/index.ts [hunk 13]
```diff
@@ -205,14 +212,21 @@ export default class CssComposer extends ItemManagerModule<CssComposerConfig & {
     width?: string,
     ruleProps?: Omit<CssRuleProperties, 'selectors'>,
   ): CssRule | undefined {
+    const key = this._makeCacheKey(selectors, state, width);
+    const cached = this._ruleCache.get(key);
+    if (cached) return cached;
```
Comment (artf) [inline packages/core/src/css_composer/index.ts]: same as above in add

File: packages/core/src/selector_manager/index.ts [hunk 14]
```diff
@@ -152,16 +150,34 @@ export default class SelectorManager extends ItemManagerModule<SelectorManagerCo
     );
     this.model = new Model({ cFirst: config.componentFirst, _undo: true });
     this.__update = debounce(() => this.__trgCustom(), 0);
+
+    this._setupListeners();
+    this._onItemsReset(this.all);
```
Comment (artf) [inline packages/core/src/selector_manager/index.ts]: do we need this one?

File: packages/core/src/selector_manager/index.ts [hunk 15]
```diff
@@ -251,7 +268,14 @@ export default class SelectorManager extends ItemManagerModule<SelectorManagerCo
       name = name.substr(1);
     }
 
-    return this.all.where({ name, type })[0];
+    const key = this.getCacheKey(name, type);
+    if (this._itemCache.has(key)) {
+      return this._itemCache.get(key);
+    }
```
Comment (artf) [inline packages/core/src/selector_manager/index.ts]:
```js
const key = this.getCacheKey(name, type);
const cached = this._itemCache.get(key);
if (cached) return cached;
```

File: packages/core/src/abstract/Module.ts (hunk 4 above)
Comment (mohamedsalem401) [reply packages/core/src/abstract/Module.ts]: Yes, It only works like this. with binding + not with `this.all.on`

**Review by artf — APPROVED** [review]
💜
